messaging:
  amqp:
    player:
      exchange:
        name: TEST.TEAMBUILTING.E.PLAYER
        durable: false
        autodelete: true
      queue:
        name: TEST.TEAMBUILTING.Q.SPORTS.PLAYER
        binding: player.cud.#
        durable: false
        autodelete: true

---

auth0:
  domain: manuelarte.eu.auth0.com
  issuer: https://manuelarte.eu.auth0.com/
  clientId: XOBz4RdzWoMnpxAvXKtK9R8W9IODYKsl
  clientSecret: tvKvKZd1tigVIAGztcOELwKIj0B0DswEbLdRG1PWu7NfZXk6VGbGkWdQjFpTZmWp
  securedRoute: NOT_USED
  base64EncodedSecret: true
  authorityStrategy: ROLES
  defaultAuth0ApiSecurityEnabled: false
  signingAlgorithm: HS256
  #signingAlgorithm: RS256
  #publicKeyPath: certificate/cert.pem